services:
  web:
    build:
      context: ./django
    volumes:
      - ./django:/app/django
      - ./django/staticfiles:/app/static
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shortlink_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./django/staticfiles:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
