services:
  web:
    build:
      context: ./django
    volumes:
      - ./django:/app/django
      - ./django/staticfiles:/app/static
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  web2:
    build:
      context: ./hitungpajak
    volumes:
      - ./hitungpajak:/app/hitungpajak
      - ./hitungpajak/staticfiles:/app/static
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shortlink_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./django/staticfiles:/app/static
      - ./hitungpajak/staticfiles:/app/static2
    depends_on:
      - web
      - web2
  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/main.com:/etc/bind/zone/main.com
      - ./dns/zone/sec.com:/etc/bind/zone/sec.com
    command: named -c /etc/bind/named.conf -g -u named

volumes:
  postgres_data:
