# Generated by Django 5.0.6 on 2024-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_alter_profile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("expired", "Expired")],
                default="active",
                max_length=10,
            ),
        ),
    ]
